name: docs

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.13"
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v2
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the project
        run: uv sync --all-extras --dev --all-groups
      - name: Install packmol.jl
        run: |
          julia -e 'import Pkg; Pkg.add("Packmol")'
      - name: Install pandoc
        run: |
          sudo apt update
          sudo apt install -y pandoc
      - name: Build documentation
        run: |
            cd docs
            uv run make html
      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
            path: docs/build/html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

