name: docs

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.12"
        os:
          - ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v2

      - uses: julia-actions/setup-julia@v2

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev --all-groups

      - name: Install packmol.jl
        run: julia -e 'import Pkg; Pkg.add("Packmol")'

      - name: Install pandoc
        run: |
          sudo apt update
          sudo apt install -y pandoc

      - name: Build documentation
        run: |
          cd docs
          uv run make html

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v4
