# This workflow will install Python dependencies, run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '14 3 * * 1'  # at 03:14 on Monday.

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
        os:
          - ubuntu-latest
        packmol-version:
          - "20.15.1"

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v2
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Install packmol
        run: |
          wget https://github.com/m3g/packmol/archive/refs/tags/v${{ matrix.packmol-version}}.tar.gz
          tar -xvf v${{ matrix.packmol-version}}.tar.gz
          cd packmol-${{ matrix.packmol-version}}
          make
      - name: Install packmol.jl
        run: |
          julia -e 'import Pkg; Pkg.add("Packmol")'
      - name: Pytest
        run: |
          # add packmol to path
          export PATH=$PATH:$(pwd)/packmol-${{ matrix.packmol-version}}

          uv run python --version
          uv run pytest --cov --junitxml=junit.xml -o junit_family=legacy
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
