name: tests

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "14 3 * * 1" # at 03:14 on Monday.

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.11"
          - "3.10"
          - "3.12"
        os:
          - ubuntu-latest
        packmol-version:
          - "20.15.1"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install package
        run: |
          poetry install --no-interaction
      - name: Install packmol
        run: |
          wget https://github.com/m3g/packmol/archive/refs/tags/v${{ matrix.packmol-version}}.tar.gz
          tar -xvf v${{ matrix.packmol-version}}.tar.gz
          cd packmol-${{ matrix.packmol-version}}
          make
      - name: Pytest
        run: |
          # add packmol to path
          export PATH=$PATH:$(pwd)/packmol-${{ matrix.packmol-version}}
          poetry run python --version
          poetry run coverage run -m pytest -vv
          poetry run coverage xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
